# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5728ec942db1567198dcaff3e3811c9a130edfd0e1c51e85d33078ff0297401603ef50ccb466ca96b5bf4a3993039e83c8669c6c51ebb860db24fd4c37f26eb8

test:
  secret_key_base: c6d52c4f51bd43621644a575b01044d964c31e92a7febf017b21a942113377d595f3fa5589492dd445ee298afe9e0f08829982d96443011288298dbe5cc4db1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
